title = "CIS 19X - Go Programming"
baseurl = "http://seas.upenn.edu/~cis19x/"
languageCode = "en-us"
theme = "cis19x-theme"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Schedule"
    url = "/schedule/"

[params]
    description = "Go Programming"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Go Logo"
